CLUSTAL multiple sequence alignment by MUSCLE (3.8)


House_mouse_DDX6               MSTARTENPVIMGLSSQNGQLRGPVKASAGPGGGGTQPQPQLNQLKNTSTINNGTPQQAQ
large_cabbage_white            -----------------------------------MMTENRISAINHV-----GNSINNQ
pink_bollworm                  -----------------------------------MMTENRISSSNHV-----GNSMNNQ
migratory_locust               -----------------------------------MMTETHVNS-NHVSLLPPVNSINNQ
western_flower_thrips          --------------------------------------MTEVHS-NHV--------IGGI
Panagrolaimus_davidi_Ddx6      -----------------------------------MAVEAQNK-----------------
bovine_lungworm                ----------------------------------MSAADAKVTVT---------------
New_World_hookworm             -----------------------------------MLEIQDKRF------------KTAV
barber_pole_worm               ----------------------------------MSVADTKVAAVT--------------
African_eye_worm               -----------------------------------MTSKTESQ-----------------
dog_roundworm                  -----------------------------------MSSEAVSH-----------------
                                                                                           

House_mouse_DDX6               SMAATIK-PGDDWKKTLKLPPKDLRIKT-SDVTSTKGNEFEDYCLKRELLMGIFEMGWEK
large_cabbage_white            KGDVDKTVDDMGWKSKLKLPPKDRRMKT-SDVTDTRGNEFEEFCLKREILMGIFEKGWEK
pink_bollworm                  KGDVDKTIDDIGWKSKLKIPAKDRRIKT-SDVTDTRGNEFEEFCLKRELLMGIFEKGWEK
migratory_locust               KMDMDVT-DDKGWKSKLKIPPKDRRIQT-SDVTDTRGNEFEEFCLKRELLMGIFEKGWEK
western_flower_thrips          SMNKDLD-DGIGWKSKLKIPPKDQRIKT-SDVTDTRGNEFEEFCLKRELLMGIFEKGWEK
Panagrolaimus_davidi_Ddx6      --------TNDDWKAQLQLPAKDMRYKT-LDVTNTRGLDFEEFSLSRDLLKGIFEKGWER
bovine_lungworm                --------TDENWKSSLVIPAKDKRFKT-ADVTDTKGVEFEDFCLSRDLLMGIFEKGWEK
New_World_hookworm             LIFCPLGDASKIW----IRDYQEIDLRTLQDVTDTKGVEFEDFCLSRDLLMGIFEKGWEK
barber_pole_worm               --------TDENWKAGLVLPAKDKRFKT-ADVTDTKGVEFEDFCLSRDLLMGIFEKGWEK
African_eye_worm               --------SDQSWKENLNLPAKDLRFKT-TDVTDTKGIEFEDFCLKRPLLMGIFEKGWEK
dog_roundworm                  --------SDHSWKEGLKVPAKDMRYKT-ADVTDTKGIEFEDFCLKRDLLMGIFEKGWEK
                                        .  *        ::   .*  ***.*.* :**::.*.* :* **** ***.

House_mouse_DDX6               PSPIQEESIPIALSGRDILARAKNGTGKSGAYLIPLLERLDLKKDNIQAMVIVPTRELAL
large_cabbage_white            PSPIQEASIPIALSGKDVLARAKNGTGKTGAYCIPVIEQVDPKKDCIQALIVVPTRELAL
pink_bollworm                  PSPIQEASIPIALSGKDVLARAKNGTGKTGAYCIPVLEQVDPKKDCIQALVVVPTRELAL
migratory_locust               PSPIQEASIPIALSGKDVLARAKNGTGKTGAYSIPVLEQVDPKKDCIQALIIVPTRELAL
western_flower_thrips          PSPIQEASIPIALSGKDVLARAKNGTGKTGAYSIPVLEQVDPKKDCIQALVIVPTRELAL
Panagrolaimus_davidi_Ddx6      PSPIQEASIGIALSGQDILARAKNGTGKTGAYCIPVIERLDTSKDCIQALIIVPTRELAL
bovine_lungworm                PSPIQEASIGVALSGQDILARAKNGTGKTGAYCIPVIEKINPAIKKIQALVIVPTRELAL
New_World_hookworm             PSPIQEASIGVALSGQDILARAKNGTGKTGAYCIPVIEKINPAIKKIQALVIVPTRELAL
barber_pole_worm               PSPIQEASIGVALSGQDILARAKNGTGKTGAYCIPVIEKINPSIKKIQALVIVPTRELAL
African_eye_worm               PSPIQEASISIALSGQDILARAKNGTGKTGAYCIPCIDKVDVEKKYPQSLIIVPTRELAF
dog_roundworm                  PSPIQEASIAIALSGQDILARAKNGTGKTGAYCIPCIEKIDPELKKIQALIIVPTRELAL
                               ****** ** :****.*:**********:*** ** ::.::   .  *::::*******:

House_mouse_DDX6               QVSQICIQVSKHMGGAKVMATTGGTNLRDDIMRLDDTVHVVIATPGRILDLIKKGVAKVD
large_cabbage_white            QTSQICIELAKHT-DIRVMVTTGGTNLRDDIMRIYQNVQVIIATPGRIIDLMDKQVAKMD
pink_bollworm                  QTSQICIELAKHT-DIRVMVTTGGTNLRDDIMRIYQNVQVIIATPGRMIDLMDKQVAKMD
migratory_locust               QTSQICIELAKHM-KVKVMVTTGGTNLRDDIMRIYQTVHVVIATPGRILDLMDKHVANME
western_flower_thrips          QTSQICIELAKHM-DVKVMVTTGGTNLRDDIMRIYQKVHIIIATPGRILDLMDKNVANME
Panagrolaimus_davidi_Ddx6      QTSQICVELGKHI-GLKVMVTTGGTDLRDDILRLNSAVHLIVATPGRIIDLMEKGVAEVQ
bovine_lungworm                QTSQICVELSKHI-KLKIMVTTGGTDLRDDIMRLNGSVHMVIATPGRILDLMEKGVADMS
New_World_hookworm             QTSQICVELSKHI-KLKIMVTTGGTDLRDDIMRLNGSVHMVIATPGRILDLMEKGVADMS
barber_pole_worm               QTSQICVELSKHI-KLKIMVTTGGTDLRDDIMRLNGSVHMVIATPGRILDLMEKGVADMS
African_eye_worm               QTSNICVDLSKHM-NLKVMVTTGGTELRNDIMRLNGTVHIIVATPGRILDLMDKNVADMS
dog_roundworm                  QTSQICVELSKHL-KLKVMVTTGGTDLRDDIMRLNGIVHLVVATPGRILDLMDKGVADMS
                               *.*:**:::.**    .:*.*****:**:**:*:   *::::*****::**:.* **.:.

House_mouse_DDX6               HVQMIVLDEADKLLSQDFVQIMEDIILTLPKNRQILLYSATFPLSVQKFMNSHLQKPYEI
large_cabbage_white            QCRMLVLDEADKLLSQDFKGMLDLVISRLPKERQILLFSATFPLSVKQFMEKHLREPYEI
pink_bollworm                  QCRMLVLDEADKLLSQDFKGMLDMVISRLPKERQILLFSATFPLSVKQFMEKHLREPYEI
migratory_locust               HCRMLVLDEADKLLSQDFKGMLDHVIAQLPSERQILLYSATFPLSVKQFMEKHLRKPYEI
western_flower_thrips          NCRILVLDEADKLLSQDFKGMLDHVISRLPKERQILLYSATFPLTVKQFMEKHLKEPYEI
Panagrolaimus_davidi_Ddx6      DCKMLVLDEADKLLSQDFQGVLDRLVSFLPAGRQIMLYSATFPRTVASFMESHMKNPYEI
bovine_lungworm                HCKMLVLDEADKLLSQDFQGILDRLISFLLKERQIMLYSATFPMTVTEFMQKHMRKPYEI
New_World_hookworm             NCKMLVLDEADKLLSQDFQGILDRLISYLPKERQIMLYSATFPMTVTEFMQKHMRKPYEI
barber_pole_worm               NCKMLVLDEADKLLSQDFQGILDRLISFLPKERQIMLYSATFPMTVTEFMQKHMRKPYEI
African_eye_worm               HCTTLVLDEADKLLSQDFQGILDRVIKFLPPDRQIMLYSATFPLTVATFMQKHMRNPYEI
dog_roundworm                  RCATLVLDEADKLLSQDFQGILDRVIKFLPPERQIMLYSATFPLTVATFMQKHMRNPYEI
                                   :*************  ::: ::  *   ***:*:***** :*  **:.*:.:****

House_mouse_DDX6               NLMEELTLKGVTQYYAYVTERQKVHCLNTLFSRLQINQSIIFCNSSQRVELLAKKISQLG
large_cabbage_white            NLMEELTLKGVTQYYAFVQERQKVHCLNTLFSKLQINQSIIFCNSTQRVELLAKKITELG
pink_bollworm                  NLMEELTLKGVTQYYAFVQERQKVHCLNTLFSKLQINQSIIFCNSTQRVELLAKKITELG
migratory_locust               NLMEELTLKGVTQYYAFVQERQKVHCLNTLFSKLQINQSIIFCNSTQRVELLAKKITELG
western_flower_thrips          NLMEELTLKGVTQYYAFVQERQKVHCLNTLFSKLQINQSIIFCNSTQRVELLAKKITELG
Panagrolaimus_davidi_Ddx6      NLMEELTLLGVTQFYAFVTEKQKVHCLNTLFRKLQINQSIIFC-----------------
bovine_lungworm                NLMEELTLLGVTQYYAFVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITEIG
New_World_hookworm             NLMEELTLLGVTQYYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITEIG
barber_pole_worm               NLMEELTLLGVTQYYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITEIG
African_eye_worm               NLMEELTLVGVTQYYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITEIG
dog_roundworm                  NLMEELTLLGVTQFYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITEIG
                               ******** ****:**:* *.********** .**********                 

House_mouse_DDX6               YSCFYIHAKMRQEHRNRVFHDFRNGLCRNLVCTDLFTRGIDIQAVNVVINFDFPKLAETY
large_cabbage_white            YCCYYIHARMAQAHRNRVFHDFRAGLCRNLVCSDLFTRGIDVQAVNVVINFDFPRMAETY
pink_bollworm                  YCCYYIHARMAQAHRNRVFHDFRAGLCRNLVCSDLFTRGIDVQAVNVVINFDFPRMAETY
migratory_locust               YCCYYIHAKMAQAHRNRVFHDFRAGLCRNLVCSDLFTRGIDVQAVNVVINFDFPKMAETY
western_flower_thrips          YCCYYIHAKMAQAHRNRVFHDFRNGLCRNLVCSDLFTRGIDVQAVNVVINFDFPKMAETY
Panagrolaimus_davidi_Ddx6      ------------------------------------------------------------
bovine_lungworm                YSCYYIHSKMAQNHRNRVFHDFRQGNCRNLVCSDLLTRGIDIQAVNVVINFDFPRNSETY
New_World_hookworm             YSCYYIHSKMAQNHRNRVFHDFRQGNCRNLVCSDLLTRGIDIQAVNVVINFDFPRNAETY
barber_pole_worm               YSCYYIHSKMAQNHRNRVFHDFRQGNCRNLVCSDLLTRGIDIQAVNVVINFDFPRNAETY
African_eye_worm               YSCYYIHSRMAQGHRNRVFHDFRKGACRNLVCSDLLTRGIDIQAVNVVINFDFPRNAETY
dog_roundworm                  YSCYYIHSRMAQNHRNRVFHDFRQGNCRNLVCSDLLTRGIDIQAVNVVINFDFPRNAETY
                                                                                           

House_mouse_DDX6               LHRIGRSGRFGHLGLAINLITYDDRFNLKSIEEQLGTEIKPIPSNIDKSLYVAEYHSEPA
large_cabbage_white            LHRIGRSGRFGHLGIAINLITYEDRFALHRIERELGTEIKPIPKVIDPALYVARVSEEDD
pink_bollworm                  LHRIGRSGRFGHLGIAINLITYEDRFALHRIEQELGTEIKPIPKVIDPALYVA-RPDEDD
migratory_locust               LHRIGRSGRFGHLGIAINLITYEDRFALHRIEQELGTEIKPIPKVIDPSLYVATKIEDAQ
western_flower_thrips          LHRIGRSGRFGHLGIAINLITFDDRFALHRIEQELGTEIKPIPKVIDPALYVAKSLDDSH
Panagrolaimus_davidi_Ddx6      ------------------------------------------------------------
bovine_lungworm                LHRIGRSGRFGHLGVAINLITFEDRHTFRRIEQELRTQIEPIPKAIDPKLYFFCSSVLPC
New_World_hookworm             LHRIGRSGRFGHLGVAINLITYEDRHTLRRIEQELRTQIEPIPKAVDPKLYVADFQIVED
barber_pole_worm               LHRIGRSGRFGHLGVAINLITYEDRHTLRRIEQELRTQIEPIPKAVDPKLYVADFQIVDD
African_eye_worm               LHRIGRSGRFGHLGIAINLITYEDRFTLRRIEAELRTRIAPIPKSVDPKLYVAEYQIVDE
dog_roundworm                  LHRIGRSGRFGHLGIAINLITYEDRFTLRRIEAELRTHIAPIPKSVDPKLYVAEHQLVDE
                                                                                           

House_mouse_DDX6               EDEKP--------------
large_cabbage_white            GADK---------------
pink_bollworm                  GADK---------------
migratory_locust               GIDESNVSK----------
western_flower_thrips          AIEEANNVSK---------
Panagrolaimus_davidi_Ddx6      -------------------
bovine_lungworm                DLLCVLWMNLCVS------
New_World_hookworm             EDNNKTNAN----------
barber_pole_worm               EDNNRANAN----------
African_eye_worm               NGSEMVGSSKETAA-----
dog_roundworm                  NAENENSVGSSSSKPVAVA
                                                  
