CLUSTAL multiple sequence alignment by MUSCLE (3.8)


NP_851841.2        MSTARTENPVIMGLSSQNGQLRGPVKASAGPGGGGTQPQPQLNQLKNTSTINNGTPQQAQ
VDO27004.1         MSVADTK-----------------------------------------------------
CDJ84064.1         MSVADTK-----------------------------------------------------
CAD2123926.1       MSTA--------------------------------------------------------
KAF7637891.1       MSTA--------------------------------------------------------
Panagrolaimus      MAVE--------------------------------------------------------
KAE9554242.1       MSTE--------------------------------------------------------
                   *:.                                                         

NP_851841.2        SMAATIKPGDDWKKTLKLPPKDLRIKTSDVTSTKGNEFEDYCLKRELLMGIFEMGWEKPS
VDO27004.1         --VAAVTTDENWKAGLVLPAKDKRFKTADVTDTKGVEFEDFCLSRDLLMGIFEKGWEKPS
CDJ84064.1         --VAAVTTDENWKAGLVLPAKDKRFKTADVTDTKGVEFEDFCLSRDLLMGIFEKGWEKPS
CAD2123926.1       --VSPALSMDDWKAELNLPTKDLRFKTADVTATKGIEFEEFGLSRDLLKGIFEKGWEKPS
KAF7637891.1       --VSPTLSMEDWKAELNLPTKDLRFKTADVTATKGTEFEEFGLSRDLLKGIFEKGWEKPS
Panagrolaimus      ---AQNKTNDDWKAQLQLPAKDMRYKTLDVTNTRGLDFEEFSLSRDLLKGIFEKGWERPS
KAE9554242.1       ---IATHSDADWKASLNLPAKDGRFKTQDVTNTRGLEFEDFSLSRDLLKGIFEKGWERPS
                          .  :**  * **.** * ** *** *.* :**:: *.*:** **** ***.**

NP_851841.2        PIQEESIPIALSGRDILARAKNGTGKSGAYLIPLLERLDLKKDNIQAMVIVPTRELALQV
VDO27004.1         PIQEASIGVALSGQDILARAKNGTGKTGAYCIPVIEKINPSIKKIQALVIVPTRELALQT
CDJ84064.1         PIQEASIGVALSGQDILARAKNGTGKTGAYCIPVIEKINPSIKKIQALVIVPTRELALQT
CAD2123926.1       PIQEASIAIALSGQDVLARAKNGTGKTGAYCIPCIEKIDPSREYIQAMVVVPTRELALQT
KAF7637891.1       PIQEASIAIALSGQDILARAKNGTGKTGAYCIPCIEKIDPSREYIQAMIVVPTRELALQT
Panagrolaimus      PIQEASIGIALSGQDILARAKNGTGKTGAYCIPVIERLDTSKDCIQALIIVPTRELALQT
KAE9554242.1       PIQEASIGIALSGHDILARAKNGTGKTGAYCIPVIGRIDTSKNEIQALIVVPTRELALQT
                   **** ** :****.*:**********:*** ** : .:: . . ***:::*********.

NP_851841.2        SQICIQVSKHMGGAKVMATTGGTNLRDDIMRLDDTVHVVIATPGRILDLIKKGVAKVDHV
VDO27004.1         SQICVELSKHI-KLKIMVTTGGTDLRDDIMRLNGSVHMVIATPGRILDLMEKGVADMSNC
CDJ84064.1         SQICVELSKHI-KLKIMVTTGGTDLRDDIMRLNGSVHMVIATPGRILDLMEKGVADMSNC
CAD2123926.1       SQICVELSKHL-KIKVMVTTGGTDLRDDILRLNGVVHLVVATPGRILDLMEKGVANVTRC
KAF7637891.1       SQICVELSKHL-KIKVMVTTGGTDLRDDILRLNGVVHLVVATPGRILDLMEKGVANVSRC
Panagrolaimus      SQICVELGKHI-GLKVMVTTGGTDLRDDILRLNSAVHLIVATPGRIIDLMEKGVAEVQDC
KAE9554242.1       SQICIELGKHM-HLKVMVTTGGTDLRDDILRLNSVVHLIVATPGRILDLMEKDVAVVDKC
                   ****:::.**:   *:*.*****:*****:**:. **:::******:**::*.** :   

NP_851841.2        QMIVLDEADKLLSQDFVQIMEDIILTLPKNRQILLYSATFPLSVQKFMNSHLQKPYEINL
VDO27004.1         KMLVLDEADKLLSQDFQGILDRLISFLPKERQIMLYSATFPMTVTEFMQKHMRKPYEINL
CDJ84064.1         KMLVLDEADKLLSQDFQGILDRLISFLPKERQIMLYSATFPMTVTEFMQKHMRKPYEINL
CAD2123926.1       KTIVLDEADKLLSQDFQGVLDRLVHFMPADRQIMLYSATFPRTVESFMEKHMQRPYEINL
KAF7637891.1       KTIVLDEADKLLSQDFQGVLDRLVHFMPSDRQIMLYSATFPRTVETFMEKHMQRPYEINL
Panagrolaimus      KMLVLDEADKLLSQDFQGVLDRLVSFLPAGRQIMLYSATFPRTVASFMESHMKNPYEINL
KAE9554242.1       KMLVLDEADKLLSQDFQGVLDRLVDRLPLGRQIMLYSATFPRTVASFMQKHMHHPHEINL
                   : :*************  ::: ::  :*  ***:******* :*  **:.*:..*:****

NP_851841.2        MEELTLKGVTQYYAYVTERQKVHCLNTLFSRLQINQSIIFCNSSQRVELLAKKISQLGYS
VDO27004.1         MEELTLLGVTQYYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITEIGYS
CDJ84064.1         MEELTLLGVTQYYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITEIGYS
CAD2123926.1       MEELTLLGITQFYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITELGYS
KAF7637891.1       MEELTLLGITQFYAYVQEKQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITELGYS
Panagrolaimus      MEELTLLGVTQFYAFVTEKQKVHCLNTLFRKLQINQSIIFC-------------------
KAE9554242.1       MEELTLLGVTQFYAFVQERQKVHCLNTLFRKLQINQSIIFCNSTQRVELLAKKITELGYS
                   ****** *:**:**:* *.********** .**********                   

NP_851841.2        CFYIHAKMRQEHRNRVFHDFRNGLCRNLVCTDLFTRGIDIQAVNVVINFDFPKLAETYLH
VDO27004.1         CYYIHSKMAQNHRNRVFHDFRQGNCRNLVCSDLLTRGIDIQAVNVVINFDFPRNAETYLH
CDJ84064.1         CYYIHSKMAQNHRNRVFHDFRQGNCRNLVCSDLLTRGIDIQAVNVVINFDFPRNAETYLH
CAD2123926.1       CYYIHSKMAQQHRNRVFHEFRQGHCRNLVCSDLLTRGIDIQAVNVVINFDFPRNSETYLH
KAF7637891.1       CYYIHSKMAQQHRNRVFHEFRQGHCRNLVCSDLLTRGIDIQAVNVVINFDFPRNSETYLH
Panagrolaimus      ------------------------------------------------------------
KAE9554242.1       CYYIHSKMAQHHRNRVFHDFREGHCRNLVCSDLLTRGIDIQAVNVVINFDFPRNSETYLH
                                                                               

NP_851841.2        RIGRSGRFGHLGLAINLITYDDRFNLKSIEEQLGTEIKPIPSNIDKSLYVAEYHSEPAED
VDO27004.1         RIGRSGRFGHLGVAINLITYEDRHTLRRIEQELRTQIEPIPKAVDPKLYVADFQIVDDED
CDJ84064.1         RIGRSGRFGHLGVAINLITYEDRHTLRRIEQELRTQIEPIPKAVDPKLYVADFQIVDDED
CAD2123926.1       RIGRSGRFGHLGIAINLITYEDRYNLKRIEKELRTHIEPIPKEVDPKLYVAEHQME----
KAF7637891.1       RIGRSGRFGHLGIAINLITYEDRYNLKRIEKELRTHIEPIPKEVDPKLYVAEHQME----
Panagrolaimus      ------------------------------------------------------------
KAE9554242.1       RIGRSGRFGHLGIAINLITYEDRHNLRRIEKELRTRIEPIPAEVDPKLYVAEYQQDLKDE
                                                                               

NP_851841.2        EKP----
VDO27004.1         NRANAN-
CDJ84064.1         NNRANAN
CAD2123926.1       -------
KAF7637891.1       -------
Panagrolaimus      -------
KAE9554242.1       DVQSSK-
                          
