---
title: "Class06"
author: "Alexander Liu"
format: pdf
---

```{r}
# Example input vectors to start with
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)
student3 <- c(90, NA, NA, NA, NA, NA, NA, NA)

gradebook <- read.csv("student_homework.csv", row.names = 1)
gradebook

``` 


```{r}
mean(student1)
```
```{r}
min(student1)
```


```{r}
# Q1 
grade <- function(scores){
  # convert NA to 0
  scores[is.na(scores)] <- 0
  # dropping the lowest
  scores_lowest_dropped <- scores[-which.min(scores)]
  # calculate average score dropping the lowest
  average <- sum(scores_lowest_dropped)/length(scores_lowest_dropped)
  # return grade
  print(average)
}

grade(student1)
grade(student2)
grade(student3)

```

```{r}
# Q2
ans <- apply(gradebook, 1, grade)
which.max(ans)
```
# student 18 is the top-scoring.


```{r}
# Q2 alternative
for (i in 1:20){
  grade(gradebook[i,])
}
```

```{r}
# Q3
mask <- gradebook
mask[is.na(mask)] <- 0
which.min(apply(mask, 2, mean))

# hw2 has the lowest average.
```
# hw2 has the lowest average, thus considered to be the toughest homework.


```{r}
# Q4
cor(mask$hw2, ans)
which.max(apply(mask, 2, cor, ans))

```
# hw5 is considered to be the most predictive.
